import Head from "next/head";
import HomeProducts from "../components/Homepage/HomeProducts";
import { useEffect } from "react";
import Loader from "../components/layout/Loader";
import Contact from "../components/footer";

export default function Home({ data }) {
  return (
        <div>
          <Head>
            <title>shopgrid</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/logo.svg" />
          </Head>
          <main className="">
            <HomeProducts products={data.products} />
          </main>
          <Contact/>
        </div>
      )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(
    `${process.env.NEXT_PUBLIC_GITPOD_HOST}/api/products`
  );
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
