export const GET_ALL_PRODUCT_ADMIN_REQ = "GET_ALL_PRODUCT_ADMIN_REQ" 
export const GET_ALL_PRODUCT_ADMIN_SUCCESS = "GET_ALL_PRODUCT_ADMIN_SUCCESS" 
export const GET_ALL_PRODUCT_ADMIN_FAIL = "GET_ALL_PRODUCT_ADMIFAILEQ" 

export const DELETE_ADMIN_PRODUCT_REQ = "DELETE_ADMIN_PRODUCT_REQ"
export const DELETE_ADMIN_PRODUCT = "DELETE_ADMIN_PRODUCT"
export const DELETE_ADMIN_PRODUCT_FAIL = "DELETE_ADMIN_PRODUCT_FAIL"

export const ADMIN_USER_REQ = "ADMIN_USER_REQ"
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS"
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL"