export const CREATE_PRODUCT_REQ = "CREATE_PRODUCT_REQ";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";


export const ALL_PRODUCT_REQ = "ALL_PRODUCT_REQ";
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS";
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL";


export const SINGLE_PRODUCT_REQ = "SINGLE_PRODUCT_REQ";
export const SINGLE_PRODUCT_SUCCESS = "SINGLE_PRODUCT_SUCCESS";
export const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";


export const REVIEW_PRODUCT_REQ = "REVIEW_PRODUCT_REQ";
export const REVIEW_PRODUCT_SUCCESS = "REVIEW_PRODUCT_SUCCESS";
export const REVIEW_PRODUCT_FAIL = "REVIEW_PRODUCT_FAIL";